f = open("010Files.py", 'w')
f.write("print('Hello World!')\n")
f.close()
f = open("010Files.py", 'r')
content = f.read()
print("Contents of the file after writing:")
print(content)
f.close()
f = open("010Files.py", "a")
f.write("### This is an appended item.\n")
f.close()
f = open("010Files.py", "r")
content = f.read()
print("\nContents of the file after appending : ")
print(content)
f.close()